# permissions for end users to view hasapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hasapplication-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - hasapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - hasapplications/status
  verbs:
  - get
