# permissions for end users to edit hasapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hasapplication-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - hasapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - hasapplications/status
  verbs:
  - get
