# permissions for end users to view hascomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hascomponent-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - hascomponents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - hascomponents/status
  verbs:
  - get
