# permissions for end users to edit hascomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hascomponent-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - hascomponents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - hascomponents/status
  verbs:
  - get
