# permissions for end users to view haspushes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haspush-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - haspushes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - haspushes/status
  verbs:
  - get
