# permissions for end users to edit haspushes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: haspush-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - haspushes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - haspushes/status
  verbs:
  - get
