# permissions for end users to edit pushes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: push-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - pushes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - pushes/status
  verbs:
  - get
