# permissions for end users to edit hasservicedetectionqueries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hasservicedetectionquery-editor-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - hasservicedetectionqueries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - hasservicedetectionqueries/status
  verbs:
  - get
