
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- verbs:
    - get
    - list
    - create
  apiGroups:
    - persistentvolumeclaims
    - persistentvolumeclaims/status
- verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
  apiGroups:
    - tekton.dev
  resources:
    - pipelineruns
- apiGroups:
    - triggers.tekton.dev
  resources:
    - eventlisteners
    - triggers
    - triggertemplates
  verbs:
    - create
    - update
    - patch
    - delete
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applications/finalizers
  verbs:
  - update
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - appstudio.redhat.com
  resources:
  - componentdetectionqueries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - componentdetectionqueries/finalizers
  verbs:
  - update
- apiGroups:
  - appstudio.redhat.com
  resources:
  - componentdetectionqueries/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - appstudio.redhat.com
  resources:
  - components
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - components/finalizers
  verbs:
  - update
- apiGroups:
  - appstudio.redhat.com
  resources:
  - components/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - appstudio.redhat.com
  resources:
  - pushes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - pushes/finalizers
  verbs:
  - update
- apiGroups:
  - appstudio.redhat.com
  resources:
  - pushes/status
  verbs:
  - get
  - patch
  - update
