name: Code Coverage Report
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run Go Tests
        run: |
          # Temporarily adding a pact-go installation. 
          # It should be gone once https://issues.redhat.com/browse/HAC-4879 is solved
          go get github.com/pact-foundation/pact-go/v2@2.x.x
          go install github.com/pact-foundation/pact-go/v2@2.x.x
          sudo /home/runner/go/bin/pact-go -l DEBUG install 

          go mod download
          make test
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
